# This file was generated by GoReleaser. DO NOT EDIT.
class Xtag < Formula
  desc "Finds latest release tag which matched with given tag with x wild card (a.k.a. xtag)."
  homepage "https://github.com/haya14busa/xtag"
  url "https://github.com/haya14busa/xtag/releases/download/v1.0.0/xtag_1.0.0_Darwin_x86_64.tar.gz"
  version "1.0.0"
  sha256 "2f437f81801861149a9b5baf207665d6bb158445b463b35b88390673c52cc6d9"

  def install
    bin.install "xtag"
  end

  test do
    system "#{bin}/xtag -h"
  end
end
